### ISSUE TITLE
Had to `composer install` manually

### ISSUE THREAD

**Issue by thany** [anchorcms/anchor-cms#1020]
### Summary

There's no real need for us to `composer install` manually. It can be done from within php, but better yet: don't make it a requirement in the first place. It's only yet another thing to make sure to have installed, and yet another thing that may not work at a host. Either way, before Anchor can be uploaded to a host, folks will have to have composer installed, which requires php installed on its turn. A hassle, iyam.

### Expected Behaviour

I would've expected a release download to contain everything requiremed to get the blog running. 

### Actual Behaviour

Not only is the download incomplete, it also isn't able to automatically download and install dependencies, even though this is perfectly possible from within php.

### Context details (if applicable)

- Anchor version: 0.21.1
- Server setup: XAMPP on Win10, with Apache 2.4.12 & PHP 5.6.8 & MySQL 5.6.24
- URL: Not public

**Comment by CraigChilds94** [comment]
@thany I'm already working on a resolution for this.

Though I'm not impressed with your tone of voice in these issues. Please remember we're not on this project full-time, we're doing this in our spare time. We also need to move with the times. Composer is very popular amongst php projects and provides many more benefits than drawbacks.

But yes, I'm preparing some pre-packaged downloads so that you won't have to have composer installed.

The downloads are not "incomplete", they're just not appropriate for *YOUR* setup.

I did have a setup which automatically installed the dependencies but I removed it as I felt it was unnecessary.

Also, if you expect things to be done "correctly", then it might help if you filled out the issue templates "correctly" as you're referencing a version which does not exist.

There currently is a lack of documentation regarding the installation of these newer versions, I'm working on them this week.

**Comment by thany** [comment]
> Though I'm not impressed with your tone of voice in these issues.
Not trying to be mean, just to the point. Sorry if that didn't come across right.

> they're just not appropriate for YOUR setup.
By that, do you mean the package has different requiremens for different hosts/environments?

At any rate, I guess what I was trying to say is to better release full packages containing every dependency. It might be easier for you and for users. However upgrading might still need composer to upgrade those dependencies, I don't know. Your call ;)

**Comment by CraigChilds94** [comment]
@thany Unfortunately it did come across that way :(

I mean that most people would develop locally, having an installation of composer. And then would proceed to upload the entire project to their remote server along with the `vendor` folder which is generated by composer.

OH yeah I know that it'll be useful for those who don't have the ability to develop locally etc. My recommended method of installation is pulling the project from composer like so:

```
composer create-project anchorcms/anchor-cms anchor
```

As this ensures the dependencies are included.

fyi, I'm also working on a Docker image for people to include anchor into their Docker stacks.

**Comment by TheBrenny** [comment]
I can't remember, but I think 0.9-dev had a composer folder? Plonked it
direct to my website with no issues.

But that's just my 2c...

**Comment by saucytomato** [comment]
Can we pre-create the dependencies as a branch of the master?

**Comment by ragefuljoe** [comment]
sorry to post in closed issue, but what should we do on hosts where we don't have ssh access? E.g., most shared hosting plans.

**Comment by saucytomato** [comment]
This has come up a lot, and I think someone is going to create a packaged version that doesn't require composer, but until then, you can do the composer install on your local computer and move the whole vendor folder to your installation on your host.
