### ISSUE TITLE
Posting code with an invalid language

### ISSUE THREAD

**Issue by Bibliofile** [anchorcms/anchor-cms#1091]
Using \`\`\`\`Language to create a code block can result in unsafe markup in blog posts if the language is invalid. 

### Expected Behaviour

Creating a post with an invalid language should drop the language

### Actual Behaviour

Creating a post containing
\`\`\`\`PHP"test\<script>alert('xxs');\</script>

Results in the HTML
\<p>\`\`\`\`PHP&quot;test\<script>alert('xxs');\</script>

Note: This isn't a problem with comments, mostly. Since they have to be approved, and also since they are escaped properly (for the most part, that's another issue) by the CMS. This is also why I felt justified in posting this publicly. 

### Context details

- Anchor version: 0.12.1

**Comment by daviddarnes** [comment]
Thanks for reporting. However it looks like you're syntax isn't quite right, you seem to be using 4 backticks instead of 3 and not adding the 3 closing backticks. Also, the additional `<p>` is a result of the additional return you probably added above the code. See example below:
```
My line of text describing the code below
    ```
    <script>alert("This is a piece of code;</script>
    ```
```

Note: please ignore the indentation, this is just so that I can present the example code in GitHub comments

**Comment by Bibliofile** [comment]
Sorry about that, I completely missed that it required three backticks, I also didn't realize that blog posts were supposed to present HTML 'as is'. Thanks for the quick response.
