### ISSUE TITLE
Database connection details visible on connection error while installation

### ISSUE THREAD

**Issue by Radiergummi** [anchorcms/anchor-cms#1096]
I just installed the current 0.12.1 version. Seems like I made a typo in the database connection details, which produces an exception.  
**First problem**: You are presented the (although nicely formatted) exception page which provides no way to just correct the error but assumes you know you can safely use the browser back button. Kinda bad usability.  
**Second, way worse problem**: The connection details are visible in the exception text, including a potentially correct password (say I just misspelled my server name).

<img width="1277" alt="bildschirmfoto 2016-06-02 um 16 05 30" src="https://cloud.githubusercontent.com/assets/6115429/15747944/3d2add5e-28dd-11e6-8a84-99dd4284951c.png">

**Comment by Gerrit0** [comment]
While I agree that this is a problem, I believe it is less important than you thought at first. 

You can only get that page if you *just* submitted the install form. Otherwise, viewing that page will present you with blank fields to fill out, so you can't actually get a username / password from someone else's input.
