### ISSUE TITLE
CMS vs Blog

### ISSUE THREAD

**Issue by JamesGeiger** [anchorcms/anchor-cms#1108]
I am extremely new to anchor, but I would prefer to see it positioned as more of a CMS then a blogging platform. Working should not be specific to blogging, but to site building. It is a small thing, but can go a long way in terms of perception.

Thanks. 

P.S. What is the biggest need right now? I want to contribute! :)

**Comment by daviddarnes** [comment]
We do state that it's a CMS with blogging in mind, despite in certain places being stated as a blogging system. The reason is that it started as a blog system and then grew from there.

If you looking for a way to contribute, take a look at the [issues reported](https://github.com/anchorcms/anchor-cms/issues) and then look into [our contribution docs](https://github.com/anchorcms/anchor-cms/blob/master/.github/CONTRIBUTING.md)

Thanks!

**Comment by JamesGeiger** [comment]
@daviddarnes Thanks! Will the blogging references be changed to make it more agnostic?

**Comment by daviddarnes** [comment]
Possibly, probably when v1.0 hits

**Comment by JamesGeiger** [comment]
@daviddarnes sweet! I haven't been this excited by a CMS in a while. Was so used to WordPress (which has become pretty bloated) and Drupal (which is confusing).
