### ISSUE TITLE
"Directive 'magic_quotes_gpc' is deprecated in PHP 5.5 and greater"

### ISSUE THREAD

**Issue by WuGGu** [anchorcms/anchor-cms#1137]
Hi everyone,

i try to install anchor on my webspace.

Webspace is running with PHP 5.6. Installer worked fine. Created a database. But on every screen i get this error.

Directive 'magic_quotes_gpc' is deprecated in PHP 5.5 and greater
The error has been logged in /anchor/errors.log
Uncaught Exception
Directive 'magic_quotes_gpc' is deprecated in PHP 5.5 and greater
Origin
on line 0
Trace
#0 [internal function]: System\Error::shutdown()
#1 {main}

Thanks for help

**Comment by TheBrenny** [comment]
I don't think this is an issue with Anchor, but more an issue with how you have your webserver set up. `magic_quotes_gpc` is a PHP module that can be turned on an off. The reason that this is only a warning, is that because PHP is picking this up, and throwing an error.

To remove it, PHP.net have excellent documentation: http://php.net/manual/en/security.magicquotes.disabling.php

**Comment by Gerrit0** [comment]
For the record, for anyone who can't change this due to shared hosting - 

In `system/boot.php` remove lines 41-47 - as magic quotes is already turned off removing these lines does no harm.
