### ISSUE TITLE
Extend is wiping custom fields with images/files in them them on edit/save.

### ISSUE THREAD

**Issue by robmilnes** [anchorcms/anchor-cms#1150]
### Summary

1) Create custom Image field for pages.
2) Go to pages, create new.
3) Select picture to upload in new custom field.
4) Save it - this works fine.
5) Edit said page, without touching custom field.
6) Save it, all fields with images in the are wiped clean.

You then have to reupload the image and save it again. Every time you save a page after editing, the images are wiped from custom fields. It only seems to do it on fields that handle files.
### Expected Behaviour

The image/file should remain, when page is being saved - unless you physically click delete.
### Actual Behaviour

Previously uploaded images/files are cleaned out of the field, and out of the json array in the database table 'yourprefix_page_meta'
### Context details (if applicable)
- Anchor version: 0.12.1
- Server setup: Centos VPS

**Comment by daviddarnes** [comment]
Well this is pretty crappy, sorry you've hit this bug. Thanks for reporting it.

**Comment by TheBrenny** [comment]
There was a bug a while ago regarding the same sort of issue, only that bug said that files and images were never saved in the first place.

I'll flick through a fresh install and see what I can find.

**Comment by evansharp** [comment]
I can confirm this bug, having the exact same issue.

**Comment by EmgrtE** [comment]
+1 same issue.

**Comment by evansharp** [comment]
Decided to have a crack at this, since it's a big deal for my site. I haven't looked at the Anchor codebase before, so bear with me while I get my head into it ...

Right off the bat I notice something strange in the Extend model:
In both the `value()` and `html()` methods, there is no code in the switch block for `$item` type "image". This is around lines 55, and 95. Methods arn't documented though, so I'm not totally sure what they are supposed to do yet.
