### ISSUE TITLE
how to fix this problem?

### ISSUE THREAD

**Issue by haxord7** [anchorcms/anchor-cms#1201]
how to fix this problem

<a href="http://imgur.com/EVjOmv0"><img src="http://i.imgur.com/EVjOmv0.png" title="source: imgur.com" /></a>

**Comment by TheBrenny** [comment]
@haxord7. With little to no information about the issue, there's nothing that we can really help with. Start by following the [issue template](https://github.com/anchorcms/anchor-cms/blob/master/.github/ISSUE_TEMPLATE.md) when reporting an issue with Anchor, rather than just pasting a photo in. This will allow us to better pinpoint the issue at hand.

But rather than creating a new issue, could I get you to answer the following questions:
1. What version of Anchor are you using, and where did you source this version from?
2. What's your server setup? Are you using MySQL? Are you using PHP 7? This helps us to understand the context of your server and sets the basis of where we go from here.

Answering these questions will allow us to more effectively solve your problem.

**Comment by daviddarnes** [comment]
@TheBrenny @haxord7 it would've been helpful to fill in the the New Issue Template that's provided when anyone makes a new issue:

### Summary

A brief but detailed explanation of the issue or bug you are reporting.

### Expected Behaviour

- A list of steps you expected to happen in order

### Actual Behaviour

- A list of steps you actually encountered

### Context details (if applicable)

- Anchor version:
- Server setup:
- URL:
