### ISSUE TITLE
Stored XSS in anchor-cms

### ISSUE THREAD

**Issue by security-provensec** [anchorcms/anchor-cms#1298]
Affected software: Anchor CMS 0.12.7

Type of vulnerability: XSS (Stored XSS)

Discovered by: Provensec

Website: http://www.provensec.com

Author: Balvinder Singh

Description: Anchor CMS is prone to a Persistent Cross-Site Scripting attack that allows a malicious user to inject HTML or scripts that can access any cookies, session tokens, or other sensitive information retained by your browser and used with that site.

Vulnerable URL:
http://localhost/anchor-cms-0.12.7-bundled/anchor-cms-0.12.7/admin/posts/edit/1

Vulnerable parameter:
Description

Proof of concept:
Step1: Login into the anchor cms.

Step2:URL:http://localhost/anchor-cms-0.12.7-bundled/anchor-cms-0.12.7/admin/posts/edit/1
Go to the posts section and click on the description, and insert something with malicious javascript.

![xss_1_desc_parameter_](https://user-images.githubusercontent.com/41563984/47948081-b365be00-df4f-11e8-9dfd-8efa2f99d78a.PNG)
Step3: Here the xss got executed.

![xss_2_exected](https://user-images.githubusercontent.com/41563984/47948085-bcef2600-df4f-11e8-821a-e1eb0a32025c.PNG)

**Comment by Radiergummi** [comment]
@security-provensec As @Bibliofile mentioned, this is indeed not an XSS vulnerability. AnchorCMS allows HTML in pages and posts by design, since itis built as an easy CMS for designers and developers which might want to include scripts or stylesheets on individual pages, which is perfectly fine for us. **We even advertise this fact right on the front page of [anchorcms.com](https://anchorcms.com).**  
For projects that must cope with potentially malevolent input from their own users, another CMS might be a better fit.  
I'd encourage you to take a deeper look into open source projects before reporting CVEs to avoid false positives and damaging your reputation.

**Comment by security-provensec** [comment]
Hi @Radiergummi,
Thanks for the reply, I would like to inform you that you have to put some sanitization on the input field so that the HTML characters are properly sanitized.

With Kind Regards
Security Provensec

**Comment by daviddarnes** [comment]
@security-provensec did you actually read @Radiergummi comment properly? Sanitisation is not necessary as the main content area intentionally accepts regular markup. Additionally, XXS attack would be somewhat redundant if the attacker already has access to the admin interface
