### ISSUE TITLE
Error at last step of fresh install

### ISSUE THREAD

**Issue by oilvier** [anchorcms/anchor-cms#1303]
### Summary

I am trying to install Anchor version 0.12.7 on my webhost, but I have an error at the last step.

### Expected Behaviour

Completion of the install process

### Actual Behaviour

I am shown the following error : 

```
SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation
```

### Context details (if applicable)

- Anchor version: 0.12.7
- Server setup: PHP 5.6, mySQL 5.5 on a shared server

**Comment by oilvier** [comment]
Maybe it is because I do not have enough privileges on my database ?
My hosting provider does not allow to change this, unfortunately.

Do you think it could be it ?

**Comment by eurovirt** [comment]
Hi Oliver, have you tried contacting your hosting provider about the issue? It is indeed because you have not enough privileges to run a certain query. I suggest you try to manually run this sql file. Make sure you replace {{prefix}} with whatever prefix you entered during installation. Now, when an error occurs MySQL will return an error message with a line of the query that triggered the error. 

https://github.com/anchorcms/anchor-cms/blob/master/install/storage/anchor.sql

**Comment by oilvier** [comment]
Hi,

I have run the sql file.

```
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `anchor_comments` (
  `id` int(6) NOT NULL AUTO_INCREMENT,
  `pos' at line 9
```
My database is in MySQL 5.5, if I understood correctly other issues, the latest version of Anchor needs a more recent MySQL version ?

I think I will stick with version 0.9 for the moment because I don't want to change my hosting provider yet. And my blog is not active anymore, I just want to keep it for the memories.
