### ISSUE TITLE
Unable to use post loop on homepage

### ISSUE THREAD

**Issue by daviddarnes** [anchorcms/anchor-cms#264]
Not sure whats happening. It knows to its the homepage but no normal post loop I use seems to work on it, isn't able to find a post.

**Comment by Mullazman** [comment]
I've been trying to replicate this today, outputting posts to a specific page would be great. I tried creating my own custom attribute then running a post loop from the page if the attribute was set with the text name of the category of posts, but I can't for the life of me figure out how to do that because the post loop is done outside of a template :/
