### ISSUE TITLE
Add support for post tags

### ISSUE THREAD

**Issue by Vel0x** [anchorcms/anchor-cms#537]
This could be done along side the categories feature, or replace the categories feature. Essentially a post can have multiple tags, rather than be limited to a single category.

**Comment by digitalesherz** [comment]
@srccd managed to build #538 in @anchor already: http://hi.srccd.com/post/thats-right-tags-in-anchor

**Comment by mrmlnc** [comment]
It seems to me that this should be in CMS (Out of the box feature).

**Comment by digitalesherz** [comment]
yea i think so also.

but for the time being it's really easy to maintain tags with srccd's tutorial

**Comment by CraigChilds94** [comment]
I believe this IS something that will available in 1.0 out of the box. The community is great and the features you guys implement help us out greatly!

**Comment by CraigChilds94** [comment]
http://feathub.com/anchorcms/anchor-cms/+3

**Comment by jamestaylr** [comment]
So what's the current status on this? I feel like this issue was closed without much resolution.

Is there a PR of @digitalesherz changes? Why has this not made its way into the official build yet?

**Comment by TheBrenny** [comment]
@jamestaylr, on behalf of myself only, I haven't looked into this too much, because to build a tag system that is minimalistic while staying speed and space efficient, and keeping user friendliness, is something that would require a large amount of time and effort, which neither is available to me at this moment. To avoid data redundancy a new table would be made, but that can slow down speed, as well as still increase the size of anchor. To ensure the user friendliness would mean that users should be able to make new tags right from the post screen, which would need a lot of work itself, and there'll be plenty of AJAX requests.

I'll probably look into this towards the end of the year.
