### ISSUE TITLE
Feature: Disqus comments option

### ISSUE THREAD

**Issue by Albert221** [anchorcms/anchor-cms#776]
A good idea would be to add disqus comments and in settings you can switch between default comments' system and Disqus.

**Comment by Mullazman** [comment]
I second this very much. I tried implementing the comment confirmation part of discus into the "comments" section of the admin panel too, but to no avail without serious destruction of some core code. A proper plugin system would allow me to write some really useful plugins that Anchor muchly needs.

**Comment by TheBrenny** [comment]
Agreed. Try whip up something quickly that wouldn't *destroy* the core code, but merely allow you to extend functionality... So instead of writing 10 lines of code in an admin view, do a PHP `require` to your plugin's admin view. There you wont be *destroying* the code, but just adding one line per file. Obviously, this solution isn't permanent, but it can work.

Also, shouldn't this issue be closed, now that we've answered the topic?

**Comment by daviddarnes** [comment]
@TheBrenny I think you're right about closing, but we need to document what plugins people want.
