### ISSUE TITLE
Pagination/Pages Bug

### ISSUE THREAD

**Issue by simoncla** [anchorcms/anchor-cms#839]
There is something wrong with the 'Pages' view. 
It won't display all the pages. 

![anchor-sql](https://cloud.githubusercontent.com/assets/1838429/7085944/8b3eca82-df73-11e4-93af-652166a100c9.png)
![anchor-admin](https://cloud.githubusercontent.com/assets/1838429/7085943/8b3961e6-df73-11e4-9992-dd664d18653a.png)

After changing the 'Posts per page' option from **all** to display **4** in meta options the pagination comes up but still not displaying all of the pages.

![anchor-admin2](https://cloud.githubusercontent.com/assets/1838429/7085945/8b3efcfa-df73-11e4-9562-6e43f9fc24ca.png)

**Comment by simoncla** [comment]
Looks like the problem is orientated around the 'parent'.
If I remove all parents from the pages it displays all of them.

**Comment by csengineer13** [comment]
There have been a number of bugs/issues around the parent --> child structure. I'll take a peak at this sometime this weekend and see if its related or something new.

**Comment by simoncla** [comment]
Awesome cheers :)

**Comment by coelmay** [comment]
This is still an issue. Have attached an image of my pages, with comments. Don't know if it will be of any help...
<img width="640" alt="anchor-cms-pages-with-text" src="https://cloud.githubusercontent.com/assets/14990463/11262056/855abff0-8e72-11e5-9fc8-967cceeed91b.png">

My *workaround* is to add an *edit page* link to the footer of each page when I am logged in as admin.

**Comment by TheBrenny** [comment]
I think that this requires a whole lot more logic behind it, than what I've implemented... There's a lot do, but unfortunately, I can't really implement a fix until January.

**Comment by CraigChilds94** [comment]
@TheBrenny @coelmay I made some changes to this last night; try pulling down `0.10-dev` and let me know if it changes?

**Comment by CraigChilds94** [comment]
@coelmay Though I think the pagination for this still needs re-working as it only takes into account the count of the parent pages.

**Comment by coelmay** [comment]
@CraigChilds94 Two issues with 0.10-dev

1. In `system/start.php` there is `require PATH . 'vendor/autoload' . EXT;` and no *vendor* directory exists.
2. Pressed *complete* on fresh install, got `Class 'RandomLib\Factory' not found` Origin `system/helpers.php on line 58`

Should this be started as a separate issue?

**Comment by Prkns** [comment]
I've only just noticed this same issue. I was having the same problem as @coelmay with the duplicated and wrongly placed child pages. It has somehow now managed to completely hide these pages without any direct interaction with the page structure.

I was looking into this and wondering whether it had anything to do with the custom template that i was using. My structure has a parent page called "Work" and i've just created a template called 'page-work.php'... From what i can see, the pages have vanished since making this template?

**Comment by daviddarnes** [comment]
@Prkns sorry you've encountered this issue. @TheBrenny do you know how far we got with this? I see that there's a related issue.

**Comment by TheBrenny** [comment]
AFAIK, this is fixed in 0.9-dev, but I also have a branch in my fork. If
you're going to merge that in, you might want to look at the diffs and grab
them.

**Comment by Prkns** [comment]
@daviddarnes @TheBrenny - It's not a problem... i've added a work around of having an 'Edit Page' link when logged in so that i can still edit the pages despite them being missing from the admin area. I'm still in the process of building my site so i'm not stressing about this currently.

I still feel like Anchor is worth the slight issues that i'm facing so i'm not too fussed.

**Comment by daviddarnes** [comment]
@Prkns why aren't all our users like you? ;)

**Comment by TheBrenny** [comment]
@Prkns You're awesome. Fullstop.

@daviddarnes the main issue that went wrong I think was the mixup in
branches, where bug fixes were pushed to master and features into
0.9-dev/0.10-dev. But I can't really see a fix for this issue. Apart from
having a stable and a different branch. Where we tackle issues/features one
at a time... But then people can't really help unless we manually merge
diff's. :L

**Comment by Prkns** [comment]
@daviddarnes @TheBrenny I understand that the community will be working on Anchor alongside (probably) very hectic paid day jobs and Anchor is simply a side project.

I'm excited for Anchor to grow and become something special, if waiting a few weeks, months, (dare i say it) years for it to grow... that's worth it in my opinion. I could use the stable release granted, but seeing and testing all of the new functionality and addons is always fun ;)

Keep up the great work... i'm looking forward to maybe getting involved somewhere down the road. Although my skills are generally around the front-end/styling side of projects.

**Comment by CraigChilds94** [comment]
@TheBrenny yeah the branches are a mess because life. lol. I'm trying to sort them out and should be fine now; sticking with `pre-1.0-develop` for anything up to `1.0` and `develop` for `1.0` development.

@Prkns Thanks for understanding dude, and every little helps! If you find front-end issues just make a PR. We're happy for people to help out!

As far as this issue goes, it's fixed in the current dev branch which will hopefully have a release soon so no one should be getting this issue anymore.
