### ISSUE TITLE
Bug: Pagination not part of translation

### ISSUE THREAD

**Issue by romerojp** [anchorcms/anchor-cms#846]
As I started translating a more mexican spanish version of Anchor CMS I noticed that even though we have 

	// pagination
	'next' => 'Siguiente',
	'previous' => 'Anterior',
	'first' => 'Primero',
	'last' => '&Uacute;ltimo',

in language/(language name)/global.php

The translated values aren't used, and I've seen hotfixes in the posts.php file of the theme (something like this).

	<?php echo posts_next('Siguiente &rarr;'); ?>
	<?php echo posts_prev('&larr; Anterior'); ?>

Shouldn't this pull the translations instead? Feels awkwardly repetitive and it still doesn't fix pagination inside the admin stuff to translate

**Comment by CraigChilds94** [comment]
There may be hardcoded strings throughout the CMS that still don't use the translation values, this shall be fixed over time but thank you for making us aware of these :)

**Comment by giacomocerquone** [comment]
I would like to propose a better idea. I was building the theme that I will use for my blog and I noticed actually that the functions posts_prev() and posts_next() return an "a" tag with even an arrow. I find this a bad idea for many reasons: it forces theme maker to stick with the format that the functions provide, it is harder to style, it add useless html markup, it makes the php code heavier to make it translatable. I think it'd be better if those functions would return just the link. So instead of this situation:

`<div id="prev"> <?php echo posts_prev(); ?> </div> `

We would have this situation that I think is far better:

`<a href="<?php echo posts_prev(); ?> ">text that you want translated</a>`

If it's ok for you, I'll do a PR.

**Comment by TheBrenny** [comment]
@giacomocerquone, that's probably a different issue in itself. Open a new issue, make the changes and then PR! :)

**Comment by CraigChilds94** [comment]
@romerojp I've fixed this here: https://github.com/anchorcms/anchor-cms/commit/cd25decaef84f725bb93a3b5ba428e1e96b38ace
