### ISSUE TITLE
Uncaught Exception when deleting 'Posts' post.

### ISSUE THREAD

**Issue by notklaatu** [anchorcms/anchor-cms#855]
I decided to go with Pages-only (ie, not blog posts, just pages), so I deleted the 'Posts' page (thinking I did not need it any more) and Anchor is now unusable. Trying to go to the installation from a web browser, I only get this error:

Trying to get property of non-object
Origin

anchor/views/partials/header.php on line 47
Trace

#0 /home/content/05/12568305/html/handbook/anchor/views/partials/header.php(47): System\Error::native(8, 'Trying to get p...', '/home/content/0...', 47, Array)
#1 /home/content/05/12568305/html/handbook/system/view.php(87): require('/home/content/0...')
#2 /home/content/05/12568305/html/handbook/system/view.php(72): System\View->render()
#3 /home/content/05/12568305/html/handbook/anchor/routes/pages.php(21): System\View->partial('header', 'partials/header')
#4 [internal function]: {closure}()
#5 /home/content/05/12568305/html/handbook/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /home/content/05/12568305/html/handbook/system/router.php(152): System\Route->run()
#7 /home/content/05/12568305/html/handbook/system/start.php(36): System\Router->dispatch()
#8 /home/content/05/12568305/html/handbook/index.php(33): require('/home/content/0...')
#9 {main}

**Comment by CraigChilds94** [comment]
I think it's because you had the posts page set as the home view and therefor causing `$home` on line `47` to not be an object. If you can, access your database via something like phpmyadmin or sequel pro and alter the `home_page` field in `anchor_meta` to have the same ID as your desired page; you should be able to find this in `anchor_pages`.

Anchor isn't design to not have a posts page as it is after all a blogging CMS. If you have anymore issues then please let us know :)

It'd be great to know which version you're running also.

**Comment by notklaatu** [comment]
That makes sense, yes.
I was running 0.9.2 on RHEL 7 + Apache.

I ended up going with Dokuwiki just because, as you said, Anchor is focused on blogging. But I do intend to return to Anchor when I go a'blogging; it's really really nice!
