### ISSUE TITLE
File uploads in custom fields don't work

### ISSUE THREAD

**Issue by wollac11** [anchorcms/anchor-cms#861]
In both the current master and the 0.9-dev branches the file uploads for custom fields do not work (drag and drop to add images into the content area does). With the 0.9.2 stable version from the anchorcms site, the inverse is true. I have tested these on clean installs to verify it wasn't any of my content or my themes causing this.

When attempting to upload there is no error just no upload happens at any point and when you re open the page or post after pressing save the field is blank.

**Comment by CraigChilds94** [comment]
I came across this issue the other day when I was trying to fix something else. I was working on a fix but I couldn't find the cause of the issue. It seemed to be the case that `$_FILES` wasn't being populated, which suggests to the me that the form was setup incorrectly. This is on my list of things to do and my current dev setup is attempting to fix this.

Thanks for making us further aware of this issue.

**Comment by Kisaure** [comment]
I've got the same issue, everything is fine with image upload on a local install, but it don't works on a server install.

**Comment by CraigChilds94** [comment]
Hmm that's strange. I've yet to find the time to look into this, though it was bugging me. Maybe I'll re-write this section and it will work xD

**Comment by derbaeuerle** [comment]
I tracked down the error. Due to browser security specifications javascript can't access the real path to the file (http://martinivanov.net/2009/06/09/the-mystery-of-cfakepath-unveiled/). On a localhost the path would be "C:\fakepath<filename>". I don't know why Kisaure gets this error on a production system and his localhost works totally fine, because that's the inverted implementation of the specification.

On my local instance i removed the submit-event callback inside the editor.js and everything works fine.

**Comment by Kisaure** [comment]
Sorry about my last post, i'm confused : it work on my local install because I use the build available on anchorcms.com/ , it don't with the master build on git. Thanks to derbaeuerle for the help !

**Comment by wollac11** [comment]
So as @Kisaure has since stated the production vs localhost factor that was just a confusion and so the suggestion by @derbaeuerle won't fix this particular issue as this is one which occurs regardless of whether Anchor is running on a local sever or not.

Since uploads to the content area via drag and drop do initiate an upload and those in fields do not there must be some difference in the way the file addresses are handled between the two methods of submitting one and the one used by the field is broken.

However, the problem is not with editor.js since the only difference between the version in 0.9.2 (with working image uploads in custom fields) and the versions in master and 0.9-dev is the addition of AJAX form and keyboard shortcuts.

This issue also does not appear to be in custom-fields.js, and  upload-fields.js is unchanged from 0.9.2 so I think the error is on the PHP end of things rather than in the JS, however I have not found it yet.

**Comment by derbaeuerle** [comment]
@wollac11 the difference between the drag and drop and custom field upload is the usage of ``FormData``. In the master branch the form data object for the ajax request is received by ``form.serializeArray()``([line 197](https://github.com/anchorcms/anchor-cms/blob/master/anchor/views/assets/js/editor.js#L197)) which doesn't support correct file paths due to the security specification, to my knowledge. The ``dragdrop.js`` in the master branch uses ``new FormData`` and ``formData.append('file', file)`` ([line 102](https://github.com/anchorcms/anchor-cms/blob/master/anchor/views/assets/js/dragdrop.js#L102)) which supports the actual file path.

So since the merge and commit 3a3ca74 the custom field uses the ajax with the ``serializeArray`` call. Maybe that's the point we have to look at.

I didn't take a look at the 0.9.2 branch yet to compare the old custom field upload with the new ajax one. Does this branch also execute an ajax or is it a normal POST-request? If it's a normal POST-request there shouldn't be any error, because the ``$_FILES`` variable will receive the real file path.

**Comment by CraigChilds94** [comment]
@derbaeuerle for looking into this, it gives me an idea of what the problem might be. I'll take this information into consideration and see if I can get a fix up soon.

**Comment by wollac11** [comment]
Don't suppose there has been any progress in pinpointing or fixing this bug?

**Comment by TheBrenny** [comment]
@wollac11, I believe that @CraigChilds94 is fixing this bug, but he's been really busy the last few weeks.

Can I suggest a better workaround which is to host the content on a different cloud-based service? I host all my files on Google drive, which allows my website to be able to have a reasonably larger amount of traffic go to it.

I believe that this is the best option, and even when file uploads work again, I will still choose this option. I also have limited space on my website, so I would rather clutter it with posts rather than files.

**Comment by Cam** [comment]
+1

**Comment by coelmay** [comment]
Wondering what the progress of this is.
I have been looking at the problem, but have not found a solution yet.
Am really wanting to set up my site using this version, due to added functionality like pagetypes. Just need the images working too.

**Comment by TheBrenny** [comment]
@coelmay, just host your images on Google drive, or photo bucket and user the markdown image tags.

**Comment by daviddarnes** [comment]
@CraigChilds94 any update on this?

**Comment by coelmay** [comment]
@TheBrenny I would prefer to just host them on the same server as my site, rather than Google Drive :/ That's why I have my own server :)

I did as @derbaeuerle mentioned, commented out the AJAX submit, and image uploads work. WIN!

**Comment by coelmay** [comment]
@CraigChilds94 It's more of a *workaround* than a solution.

I initially did some console logging in `editor.js`, and found the image/file path was `c:\fakepath\<filepath>.<ext>`, and was running through as a `success` post when really nothing was being uploaded and should have been an `error`.

One thing I did notice, is the page title briefly changes to `undefined` on clicking save, which through logging was found to be the value of `submitProgress`. There might be something in that, there might not be.

In the end I simply commented out the **AJAX form and keyboard shortcuts** section of `editor.js` and the image/file upload works fine. Guess that means the issue is in that piece of script.

Hope this may be of some assistance.

**Comment by coelmay** [comment]
@CraigChilds94 Just tested the new AJAX upload code. Worked for me.

**Comment by thebillington** [comment]
Just setup Anchor on my personal site, thanks for such a great free CMS but I'm having a similar issue with image uploads.

When I drag the image in to upload it, nothing happens. I checked the editor.js file I had against the latest one on the github and I didn't have the AJAX code, so I tried with the AJAX code in as well. Also checked the dragdrop.js file against that on Github, and there were a lot differences so I tried the latest version of that but still no luck.

I'm still using Anchor as I love the speed of it, and I could get round the image upload issue by uploading directly to my server but would be good to get this working. Any idea why I'm still having issues even with the latest files?

Also I downloaded directly from the anchorcms website, are there a lot of differences between the version on there and the one on github? Is it worth downloading the latest git files and reuploading?

Cheers

**Comment by CraigChilds94** [comment]
I fincally got this working woop woop!

**Comment by EmgrtE** [comment]
Hello. I have a similar problem in 0.12.1.

@derbaeuerle is right. 1st problem in ajax. `form.serializeArray()` generates false path link.

2nd problem in back-end. In `/anchor/models/extend.php` on 188 line we have resizeImage() with two arguments but his call on 172 line with one argument.

I get right work of this functionality if I commented ajax in `/anchor/views/assets/js/editor.js` (start on 177 line) and added more one argument into calling `resizeImage()` on 172 line.
