### ISSUE TITLE
Unrestricted File Upload (Remote Code Execution) Vulnerability

### ISSUE THREAD

**Issue by tresacton** [anchorcms/anchor-cms#899]
I identified a vulnerability in the AnchorCMS product. I was testing 0.9.2 as this is the version is the latest release published on the AnchorCMS website, however, it is possible this issue is present in other versions as well.
 
Vulnerability:       Unrestricted File Upload (Remote Code Execution)
Preconditions:    Authentication as user of any role (i.e.: ‘Admin’, ‘Editor’, or ‘User’)
                             File Upload needs to be enabled for posts
Attack Scenario:
•         Attacker brute forces a valid username and password combination (or the attacker is a legitimate user with any role)
•         Attacker enables the file upload facility, if it isn’t already enabled
•         Attacker uploads a PHP file designed to execute shell code
•         All PHP files are automatically executed when the file is navigated to in the browser
•         The attacker gains access to the underlying server and can now execute arbitrary code in the context of the web server user account (in my case, this was the 'www' apache user account)

Note: David (from AnchorCMS) advised me to publicly disclose this by creating a GitHub issue against this repository.

**Comment by rwarasaurus** [comment]
If the attacker can't brute force the user/pass would this still be an issue?

**Comment by TheBrenny** [comment]
@rwarasaurus I'd believe so, this is related to issue #873.

I would've made something, but I don't know what each role's permissions will be. I spoke about it with @CraigChilds94 briefly, but not enough to gather the full details.

**Comment by tresacton** [comment]
Hi all,

Given that I was asked to disclose this in a public forum, and several months have passed, I'm going update the CVE entry (identifier CVE-2015-4698) with the relevant details, such as the nature of the vulnerability.

Cheers,

T.A.

**Comment by daviddarnes** [comment]
@tresacton it seems that this issue is not really an issue. The first two steps to reproduce this vulnerability is to brute force a username and password, but isn't that true with *any* system?

I don't think this requires a report.

**Comment by joshvickerson** [comment]
Well, it doesn't require brute force, necessarily. It just requires a user in any role to be logged in, meaning that a user with malicious intent could execute an attack. Seems like as good a reason as any to restrict file upload types.

**Comment by daviddarnes** [comment]
@joshvickerson I'm not saying we should take action, I just think we shouldn't be marking it as such a drastic vulnerability.

**Comment by TheBrenny** [comment]
While the two of you both have valid statements, I'd have to agree with David, here. Its not sooooo drastic, seeing as admins would only create users for the purpose of adding a comment, or creating a forum. The latter of which is not the original intent for Anchor. The former? Why not just throw in Disqus? Its free and it works, and according to the many results on Google, it works almost seamlessly. (The almost comes from needing to play around with your chosen theme to get things up and running)

**Comment by tresacton** [comment]
It is a serious vulnerability regardless. Just because a user has access to the web application interface, does not mean that they should have access to the underlying operating system, which is what happens when this vulnerability is exploited. In some cases, this may be also be the root account. 

Furthermore, bruteforcing is not necessarily required for exploitation, other attack vectors or vulnerabilities can be used to leverage or facilitate exploitation of this issue.

**Comment by tresacton** [comment]
Allow me to illustrate the severity with another attack scenario example.

Let's say I stored sensitive intellectual property, or usernames and passwords, or credit card information for customers on a server - or even, that this server was on the same network as some other machines I own that store this data. 

On the same server, I install Anchor CMS. I provide my 'content manager' with access to the AnchorCMS interface to add new HTML pages to my site. They exploit this vulnerability and now have access to the underlying operating system. With this access, they retrieve everything else that's stored on this server and/or use this server as a foothold/pivot point to further exploit the other systems and services on my network.

This is just an example. There are very many other ways that Remote Code Execution vulnerabilities can have a devastating impact. Remote Code Execution vulnerabilities are arguably one of the most severe types of vulnerabilities due to the potential consequences of compromise.

I hope this helps.

**Comment by kehugter** [comment]
> All PHP files are automatically executed when the file is navigated to in the browser

Can this be fixed for user-uploaded content then?

**Comment by TheBrenny** [comment]
Anchor is a platform that is generally used for soloists. If you have a
content manager, then you should be using something a bit more hardcore,
like WP.

**Comment by knoy** [comment]
>Its not sooooo drastic, seeing as admins would only create users for the purpose of adding a comment, or creating a forum. The latter of which is not the original intent for Anchor. The former? Why not just throw in Disqus? Its free and it works, and according to the many results on Google, it works almost seamlessly. 

>Anchor is a platform that is generally used for soloists. If you have a
content manager, then you should be using something a bit more hardcore,
like WP.

Quit trying to minimize the issue. Trying to say that people should really be using Wordpress or Disqus or whatever is a shitty way of avoiding the problem. This is a serious vulnerability and one that should be extremely easy to fix. 

Just patch the vuln.

**Comment by tresacton** [comment]
This doesn't make the issue any less severe and is rather irrelevant. Despite it being irrelevant, I would ask why there is a notion of 'roles' if this platform is for 'solosits'?

Surely, given the length of this thread, it would have been faster to just implement a patch instead of attempting to justify that "RCE is not a serious vulnerability"? 

I'm confident that your goals as developers are to create a product that follows good coding practices, and can be considered mature. Arguing about whether or not this is a serious issue (which it clearly is), is not going to help you achieve that. 

If the reason this hasn't been patched boils down to not knowing how code a patch to mitigate this high risk vulnerability, please note that OWASP is an excellent resource for developers - they provide many PHP examples for mitigating common and severe web application security issues. Alternatively, I'm sure that a quick google search would yield many results with tutorials demonstrating best practices for file and user input handling.

**Comment by Shad0wSt3p** [comment]
> If the attacker can't brute force the user/pass would this still be an issue?

This is why most companies perform internal testing - from an authorized account...they assume brute-force or account compromise has already taken place. By saying that this does not require a report at all is very foolish; and I think it being publically disclosed already means you may have put your own users at risk.

I feel like the effort involved to patch this does not even come close to the reputational loss suffered when a client/user gets stung by a public, unpatched CVE.

**Comment by kckrinke** [comment]
> I feel like the effort involved to patch this does not even come close to the reputational loss suffered when a client/user gets stung by a public, unpatched CVE.

Just echoing the above. Very well said @Shad0wSt3p

**Comment by TylerJFisher** [comment]
Hello there,

Asking your clients, and users to migrate away from AnchorCMS as a remediation for a remote code execution (RCE) vulnerability which you introduced into the code base does not seem like an adequate solution to me.

Then again, I am not too familiar with your code base, and perhaps it would be infeasible to perform proper input sanitisation?

In any event, advising your clients, and users to migrate away from your product because you're unsure of how to fix a bug seems a little silly to me. Perhaps we should follow your advice, and migrate to another platform such as Wordpress, or Drupal?

**Comment by mikepmtl** [comment]
I am only looking at Anchor, have not installed it.  But would it not be easy to simply "whitelist" what files types may be uploaded?

**Comment by TylerJFisher** [comment]
@mikepmtl That wouldn't be an appropriate solution in my opinion because then you wouldn't be able to host PHP files using AnchorCMS. I am unaffiliated with this project, but I might be able to help you all determine the appropriate remediation steps.

As a remediation, you may have to set up a blacklist of potentially dangerous functions, or use regular expressions in order to determine if something looks bad (kind of like how you detect SQLi and stored XSS), and then simply prevent users from uploading PHP files which are flagged as (potentially) malicious based on a set of criteria which you devise. 

This is an important issue though, it shouldn't be possible to own your friend Dave's box just because he's letting you look at what he's hosting on his CMS.

**Comment by kehugter** [comment]
> blacklist of potentially dangerous functions, or use regular expressions in order to determine if something looks bad

Sounds extremely weak. Why not `chmod`ing user uploads to `660`?

**Comment by TheBrenny** [comment]
All above,

I'm not saying that this isn't an issue; of course it is, and RCE can be
deadly to the server.

However, what I am saying, is that unless an attacker has managed to get
themselves into the admin panel, this is a (albeit slightly) less serious
issue.

No I am not a professional in security, and yes, all of you probably have a
lot more knowledge about security than me, so I understand that this issue
is still pretty serious.

When I was mentioned to migrate away, it was a reference to the comment
made by having a "Content Manager". If you're group/company/team is so
large that you are not uploading/creating content for yourself, *THEN* you
should use a more advanced CMS, let alone your CM might've changed to a
different CMS in the first place.

For my own knowledge, I don't understand how a file upload can result in an
RCE vulnerability. This is also why I'm thinking that this isn't as serious
as it possibly could be.

Sorry for creating a heated discussion, due to my lack of understanding in
this subject area. I'm sure a fix will be created soon, but there aren't
many contributors at the moment.

**Comment by TylerJFisher** [comment]
Why does this sound weak to you? 

By the way, I only suggested one (recommended) security control. You could do one, both, or more. You could also ensure that all PHP files are executed by a user in a chroot jail, for example.

The goal of my suggestion was more so geared towards preventing malicious files from being uploaded in the first place, however, steps clearly need to be in place in order to reduce the attack surface that an attacker has access to (which, is where your suggestions came in).

**Comment by mikepmtl** [comment]
@kehugter even with permissions of 400 PHP will still interpret it.

But there is no reason to need to keep PHP as a .php, .js, .py or whatever  file.  It can be kept as a .txt file and not interpreted at all.

**Comment by TylerJFisher** [comment]
That's totally okay, @TheBrenny. Nobody is an expert on everything. Perhaps @tresacton could demonstrate the technical proof of concept that he has prepared to illustrate how CVE-2015-4698 can be practically exploited from a non-administrative account?

That might be a logical next step forward, since it will show that largely untrusted users can take control of the system, and become an administrative user, or, well, do anything they like.

**Comment by tresacton** [comment]
`For my own knowledge, I don't understand how a file upload can result in an
RCE vulnerability. This is also why I'm thinking that this isn't as serious
as it possibly could be.
`

I'm always happy to elaborate and help any developer to reproduce results. Please give this a go:

1. create this file, call it exploit.php
```
# exploit.php
<?php
$output = shell_exec('ls -la');
echo "<pre>$output</pre>";
?>
```
2. log in as a user (even a low privilege user)
3. enable file uploads (if not already enabled), and then upload it
4. (optional) log out entirely
5. open a browser and navigate to the PHP file
6. notice that the command in the script (in this case 'ls -la') was executed on the file system, and the result of the command has been returned in your browser.

**Comment by mikepmtl** [comment]
You can easily handle this as well at the web server level.  
Simply do not pass any .php files to the PHP interpreter under a specific directory.

**Comment by aoloe** [comment]
without being a security expert, with php  the simplest and most secure solution seems to be to avoid saving uploads under their original name.

that way will also allow multiple uploads with the same name (but possibly a different content: report final.docx anyone?).

of course, you will have to store somewhere the original file name in order to serve it back under that name through a download script. (or simply add a random six letter extension that you strip on download).

a well crafted rewrite rule will allow you to define unique urls that serve the correct file (and if rewrite is deactivated no harm can be done... in the best case, the are unreachable since they should be stored outside of the document root in order to allow some access control)

**Comment by tresacton** [comment]
I could very well be misunderstanding what you wrote, but I don't understand how this mitigates the issue if the file is still being served?

**Comment by aoloe** [comment]
if there is not .php at then end (no extension), they will be served as raw text (if ever) and not executed on the server.
the attacker will see the source code of the file she has uploaded (and not the result of the script)

**Comment by daviddarnes** [comment]
I've been looking through these comments just now (it's morning where I am) and I'm appalled at the tone of voice and lack of respect on this Issue.

The reason I asked that this issue be raised on GitHub was in the hope that the open source community would come up with solutions to the problem in a mature manner. From what I can see most of us are just throwing blame around and pointing fingers.

I'm not asking for you to provide the golden bullet for this problem, especially since I wouldn't know where to start on such an issue, but I am asking if you could work together on simply providing help. Thank you.

**Comment by tresacton** [comment]
Oh ok gotchya. Could be an alright workaround. I recommend exercising caution though as it could be susceptible to null byte attacks if not implemented correctly. Please see the following link for some good approaches to mitigation: https://www.owasp.org/index.php/Unrestricted_File_Upload

**Comment by Shad0wSt3p** [comment]
> I've been looking through these comments just now (it's morning where I am) and I'm appalled at the tone of voice and lack of respect on this Issue.

Wow wait what? I've seen nothing but helpful discussion on mitigating a key vulnerability here...there has been no tone of voice - the only lack of respect for the issue here was your previous comments saying it does not deserve a report and "its not soooooo drastic."

> The reason I asked that this issue be raised on GitHub was in the hope that the open source community would come up with solutions to the problem in a mature manner.

That is exactly what's been happening. And that's out of their own time and effort, helping you. I am really, really confused as to your reply on this. As far as i'm concerned, you should be very thankful to anyone for being concerned about your app, because that's all I can see.

**Comment by Shad0wSt3p** [comment]
The security community is very happy to help out anyone without a solid knowledge and understanding of vulnerabilities. No dev is expected to know everything off the bat. However keeping an open mind and taking the humble back seat when something *is* pointed out is critical towards the cohesion of both communities.

**Comment by daviddarnes** [comment]
@Shad0wSt3p 

> Quit trying to minimize the issue. Trying to say that people should really be using Wordpress or Disqus or whatever is a shitty way of avoiding the problem. This is a serious vulnerability and one that should be extremely easy to fix.

> Just patch the vuln.

- @knoy

**Comment by tresacton** [comment]
Hi David,

Unsure if that was directed at me, but please note that I have taken time out of many of my days in an effort to help improve the security of your product and that of your users.

It is not my intention to point fingers of blame. I have much better things to do with my time and I was also a developer once. I get that you guys are providing an open source product and don't have all the time in the world for this. However it has been sitting here for the better part of 7 months. 

If I was a PHP developer I would have submitted a pull request. However, I am not a PHP developer and the best way for me to help is providing guidance. There is nothing wrong with reaching out to a wider open source community for help, but nobody up until that comment, suggested that they needed help. All that I've witnessed from the devs so far was (at least a prolonged and initial) refusal to consider that this is both legitimate as an issue and serious in nature.

If you dont understand something in a bug report or vuln disclosure it would be applaudable to reach out and ask for help or clarification. Unfortunately, ignoring an issue or downplaying its severity sends the wrong message and leaves users sorely unprotected.

Now, noting that Im not a strong php developer (if only this was Ruby :p) is there anything else I can do to help you to get this issue resolved?

**Comment by daviddarnes** [comment]
@ALL Apologies if my comment seemed harsher than intended. We've had a lot of issues raised in the past on this project and they haven't been met with much respect for the developers. I am not a major contributor to this in fact, I contribute in other areas but I don't work on the core.

@tresacton It's not directed at you. We've had a few issues reported here in the past that have been met with little respect for the original developers. At the same time I'm somewhat powerless to amend this issue as I'm not a PHP developer either, this isn't technically my project. I'm just someone who has commented a lot on this project and contributed in other areas.

@Shad0wSt3p I'm sorry, the tone of my comment was harsher than I intended. We've had some disrespectful people comment on this project and it is sometimes too much to handle. This particular Issue isn't that much of an offender.

**Comment by rwarasaurus** [comment]
I've updated the custom field upload input to only accept  png, jpg, bmp, gif, pdf file extensions which is better than accepting anything for now, ideally it should check the mime type of the file contents instead of trusting the file extension.

**Comment by daviddarnes** [comment]
I guess blind rage does work…

**Comment by matt-** [comment]
I hate to bump a closed ticket, but I thought I would kick in my advice. I have worked in security for the about the last 8 years.

1. I think limiting the extensions is a good start. You are doing this correctly with a "whitelist". There are a lot of things you don't want. php files, html files (XSS), cgi scripts,....   
2. I would create a new directory for uploads and add instructions to set the file system to not allow execution. something like: chmod 644 uploads/  (This means that the WWW user can read and write (edit) the directory, while everyone else can only read it and no one can execute files from it).
3. Create a .htaccess for the "uploads" directory that forces the files to download if you browse to them directly (prevents some content sniffing and things like that). 

Something like: 
```xml
<Location /uploads>
    Header set Content-Disposition attachment
</Location>
```

**Comment by kehugter** [comment]
Bolt has a nice nginx template: https://docs.bolt.cm/installation#nginx-configuring-virtual-host
