### ISSUE TITLE
Certificate broken for forums 

### ISSUE THREAD

**Issue by queirozfcom** [anchorcms/anchor-cms#932]
Browsers such as chrome won't even let me access the website, even if I want to take the risk:

https://forums.anchorcms.com/

**Comment by TheBrenny** [comment]
I'm using chrome and I managed to get through with no worries, after saying to take the risk. I got redirected to the home page, from which I followed the Forums link.

**Comment by TimohStudios** [comment]
Seems like an issue with the certificate. [According to this tweet](https://twitter.com/anchorcms/status/660056167909974016) the forum runs on a Let's Encrypt certificate since a couple days. Must be an issue with the setup of that I think? I believe either @kieronwilson or @CraigChilds94 set this up, maybe they can take a look at it

**Comment by rwarasaurus** [comment]
its chrome cache! https has only been enabled for the main site, if you visit http://forums.anchorcms.com it should work

**Comment by TimohStudios** [comment]
The link from the homepage refers to https. Everybody that clicks that link will get the error page. Is that intended behaviour? Can and should something be done about that?
