### ISSUE TITLE
I cannot save new post

### ISSUE THREAD

**Issue by rayanwv** [anchorcms/anchor-cms#964]
Hello I try to install anchor cms locally and everything works fine
but when I try to install it on my server it works fine but I cannot save new post or update the existing one
I make sure all requirements are on my server but I don't know what the cause of the problem.

Also, there is no error show up when I try to save the post

**Comment by daviddarnes** [comment]
Sounds like a permissions issue on the server.

**Comment by rayanwv** [comment]
I already give a permissions for anchor/config & content folders

**Comment by daviddarnes** [comment]
@rayanwv what about database permissions?

**Comment by rayanwv** [comment]
The user has all privileges.
I tried to reinstall it but still same problem 
This is my website
http://www.rayanwv.com
username: rayan
pass: test123

**Comment by TheBrenny** [comment]
I have no idea about what's going on, but it might be a good idea to check the network tab of Chrome's Inspect Element. That way you can see what's being returned.

**Comment by rayanwv** [comment]
the issue solved. I reinstall the 0.1 version and I added mbstring extension on php.ini and it works

Thank you for your help guys

**Comment by choicky** [comment]
I newly install anchorCMS toay and found same problem.  I can neither save/post a new post nor edit an existing post.

Based on this issue. I know it's because required php extensions are not installed.

I suggest that the install script detect whether required php extensions have been installed so that we can install the missing extensions in advance.

**Comment by nattybear** [comment]
If post title has non-english character, post did not saving. What should I do?
